// utils/seedCategories.js - Seed default categories

const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Category = require('../models/Category');

// Load environment variables
dotenv.config();

const defaultCategories = [
  { name: 'Technology', description: 'Tech-related posts and articles' },
  { name: 'Programming', description: 'Programming languages, frameworks, and tools' },
  { name: 'Web Development', description: 'Web development tutorials and guides' },
  { name: 'React', description: 'React.js related content' },
  { name: 'Node.js', description: 'Node.js and backend development' },
  { name: 'MongoDB', description: 'MongoDB database related posts' },
  { name: 'JavaScript', description: 'JavaScript programming' },
  { name: 'General', description: 'General blog posts' },
];

const seedCategories = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing categories (optional - comment out if you want to keep existing)
    // await Category.deleteMany({});
    // console.log('Cleared existing categories');

    // Insert default categories
    for (const categoryData of defaultCategories) {
      const existingCategory = await Category.findOne({ name: categoryData.name });
      if (!existingCategory) {
        // The slug will be auto-generated by the pre-save hook
        const category = new Category(categoryData);
        await category.save();
        console.log(`Created category: ${categoryData.name}`);
      } else {
        console.log(`Category already exists: ${categoryData.name}`);
      }
    }

    console.log('✅ Categories seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding categories:', error);
    process.exit(1);
  }
};

// Run if called directly
if (require.main === module) {
  seedCategories();
}

module.exports = seedCategories;

